// <auto-generated />
namespace autogreatsite_mvc45.Migration_Cars
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cars2015110104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cars2015110104));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011308485_cars2015-11-01-04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
