// <auto-generated />
namespace autogreatsite_mvc45.Migration_Cars
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cars_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cars_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201510241413016_cars_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
