// <auto-generated />
namespace autogreatsite_mvc45.Migration_Cars
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Car2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Car2));
        
        string IMigrationMetadata.Id
        {
            get { return "201510231723555_Car2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
